receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ${env:NEWRELIC_OTLP_ENDPOINT}
    headers:
      api-key: ${env:NEWRELIC_LICENSE_KEY}
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      exporters: [otlp,logging]
